version: "3"
services:
  backend:
    image: kevinmamar/rachaibackend:latest
    ports:
      - 8080:8080
  frontend:
    image: kevinmamar/rachaifrontend:latest
    ports:
      - 3000:3000
    links:
      - backend

networks:
  rachai_network:
    driver: bridge